title: Danli's site of documentation
description: Documentation of Danli's work as a student at University of Washington
theme: just-the-docs

url: https://danlil666.github.io/documentation

aux_links:
  "My other site: ":
    - "//danli-luo.com"
